### PR TITLE
Use memoization for D

### PR DESCRIPTION
**Pull request by yazd**
The difference making commit is the second one. It brings down execution time using LDC from 880ms to 562ms on my computer (that is a reduction of 36% of the time required).

### CODE REVIEW

**Comment by logicchains** [comment]
How are you compiling this? It seems to run slightly (5%-10%) slower for me compared to the version without memoisation.

**Comment by yazd** [comment]
I am using LDC v0.15.1 on Manjaro Linux x86_64.
`ldc -O2 -of=d -release -boundscheck=off -inline d.d && ./d`

**Comment by logicchains** [comment]
How are you compiling this? It seems to run slightly (5%-10%) slower for me compared to the version without memoisation.

**Comment by yazd** [comment]
I don't know why it might be slower for you, but in that case, I'll be closing this.

**Pull request closed without merging**
